### ISSUE TITLE
包太大了，下载不了！githup的网速没办法支持

### ISSUE THREAD

**Issue by wincsb** [LurenAA/smpHttp#1]
包太大了！下载不了！githup的网速没办法支持

**Comment by LurenAA** [comment]
> 包太大了！下载不了！githup的网速没办法支持

不好意思，我之前没有注意到这个问题，主要问题是我引入的一个Json的库，请等我这两天改一改CMake

**Comment by LurenAA** [comment]
我改了改，占最大内存的json库我没有上传，改为命令行指定位置，为了方便其他几个静态链接库我还是添加在了文件夹里

**Comment by wincsb** [comment]
感谢^_^

**Comment by wincsb** [comment]
download可以了。
clone时还是太大，估计你要把项目删了重新上传了。

**Comment by LurenAA** [comment]
我刚刚把所有的链接库都从代码中剥离出来了，让在wiki里面提供了一个百度云的链接，现在下载文件大的**主要原因是我历史提交记录的问题**，可以用这个命令
```
git clone url --depth=x   //x是近几次提交记录，比如1就是只有最新一次
```
感谢你的反馈，😙

**Comment by LurenAA** [comment]
有帮助的话，求个star，😙蟹蟹啦
